spring:
  application:
    name: "gateway-server"
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: "user-service"
          uri: "lb://user-service"
          predicates:
            - "Path=/api/v1/user/**"
        - id: "customer-service"
          uri: "lb://customer-service"
          predicates:
            - "Path=/api/v1/customer/**"
        - id: "contract-service"
          uri: "lb://contract-service"
          predicates:
            - "Path=/api/v1/contract/**"
        - id: "plan-service"
          uri: "lb://plan-service"
          predicates:
            - "Path=/api/v1/plan/**"
        - id: "billing-payment-service"
          uri: "lb://billing-payment-service"
          predicates:
            - "Path=/api/v1/billing-payment/**"
        - id: "customer-support-service"
          uri: "lb://customer-support-service"
          predicates:
            - "Path=/api/v1/customer-support/**"
        - id: "analytics-service"
          uri: "lb://analytics-service"
          predicates:
            - "Path=/api/v1/analytics/**"
        - id: "notification-service"
          uri: "lb://notification-service"
          predicates:
            - "Path=/api/notification/**"

server:
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka
    fetch-registry: true
    register-with-eureka: true
