apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    rule_files:
      - "/etc/prometheus/alert.rules.yml"

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - "alertmanager:9093"

    scrape_configs:
      - job_name: "config-server-app"
        scrape_interval: 30s
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["config-server:8089"]

      - job_name: "contract-service"
        scrape_interval: 30s
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["contract-service:8083"]

      - job_name: "user-service"
        scrape_interval: 30s
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["user-service:8081"]

      - job_name: "analytics-service"
        scrape_interval: 30s
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["analytics-service:8087"]
        
      - job_name: "customer-support-service"
        scrape_interval: 30s
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["customer-support-service:8086"]

      - job_name: "billing-payment-service"
        scrape_interval: 30s
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["billing-payment-service:8085"]

      - job_name: "plan-service"
        scrape_interval: 30s
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["plan-service:8084"]

      - job_name: "customer-service"
        scrape_interval: 30s
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["customer-service:8082"]

      - job_name: "notification-service"
        scrape_interval: 30s
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["notification-service:8088"]

      - job_name: "gateway-server"
        scrape_interval: 30s
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["gateway-server:8080"]
      
      - job_name: "discovery-server"
        scrape_interval: 30s
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["discovery-server:8888"]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/prometheus"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
          ports:
            - containerPort: 9090
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prometheus-storage
              mountPath: /prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prometheus-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
      protocol: TCP
  selector:
    app: prometheus 