spring:
  port: 8083
  application:
    name: contractservice
  config:
    import: configserver:http://config-server:8089/
  profiles:
    active: local
  cloud:
    config:
      profile: local

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # Prometheus, health, info endpoint'leri açık
  metrics:
    export:
      prometheus:
        enabled: true  # Prometheus metrikleri için etkinleştirilmiş
