spring:
  application:
    name: contractservice
  config:
    import: configserver:http://config-server:8089/
  profiles:
    active: local
  cloud:
    config:
      profile: local

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # Prometheus, health, info endpoint'leri açık
  prometheus:
    metrics:
      export:
        enabled: true
