spring:
  port: 8087
  application:
    name: analyticsservice
  config:
    import: configserver:http://config-server:8089
  profiles:
    active: local
  cloud:
    config:
      profile: local
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
