apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  labels:
    app: analytics-service
data:
  application.yml: |
    server:
      port: 8087
    spring:
      config:
        import: "configserver:http://config-server:8089"
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        health:
          show-details: always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  labels:
    app: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: rabiademirog/turkcell-analytics-service
          env:
            - name: CONFIGURL
              value: http://config-server:8089
            - name: SPRING_CLOUD_CONFIG_PROFILE
              value: prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8087
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 30
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: analytics-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  labels:
    app: analytics-service
spec:
  type: ClusterIP
  ports:
    - port: 8087
      targetPort: 8087
      protocol: TCP
  selector:
    app: analytics-service 