spring:
  application:
    name: planservice
  config:
    import: configserver:http://config-server:8089
  profiles:
    active: local
  cloud:
    config:
      fail-fast: false
      retry:
        initial-interval: 1500
        max-interval: 10000
        max-attempts: 10
      profile: local
      request-connect-timeout: 5000

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # Prometheus, health, info endpoint'leri açık
  prometheus:
    metrics:
      export:
        enabled: true
