configurl: http://localhost:8089
server:
  port: 8084

spring:
  application:
    name: plan-service
  cloud:
      config:
        profile: local
  config:
    import: configserver:${configurl}
  datasource:
    url: jdbc:postgresql://localhost:5434/plan-service
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddlAuto: update
  services:
    customer:
      url: http://localhost:8082
    billing-payment:
      url: http://localhost:8085
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    enpoint:
      health:
        show-details: always
    metrics:
      export:
        prometheus:
          enabled: true
    tracing:
      sampling:
        probability: 1.0
    zipkin:
      tracing:
        endpoint: "http://localhost:9411/api/v2/spans"
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full