spring:
  application:
    name: plan-service
  cloud:
    config:
      uri: http://localhost:8089
      profile: local
  config:
    import: configserver:http://localhost:8089
  profiles:
    active: dev
server:
  port: 8084
