spring:
  port: 8086
  application:
    name: customersupportservice
  config:
    import: configserver:http://config-server:8089
  profiles:
    active: local
  cloud:
    config:
      profile: local

