spring:
  application:
    name: user-service

  config:
    import: optional:configserver:http://config-server:8089

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8888/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    hostname: user-service

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  health:
    probes:
      enabled: true

  metrics:
    export:
      prometheus:
        enabled: true  # Prometheus için metrikleri açar

