server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userservice
    username: postgres
    password: test 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    open-in-view: false  # OSIV (Open Session in View) pattern'i devre dışı bırakır


