spring:
  application:
    name: "discovery-server"

server:
  port: 8888

eureka:
  instance:
    hostname: "localhost"
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka"
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # Prometheus, health, info endpoint'leri açık
  prometheus:
    metrics:
      export:
        enabled: true
