apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: test
  POSTGRES_DB: postgres


# TERMİNALDE
# kubectl apply -f [bu dosyanın yolu]
# sonrasında --> kubectl get config yazarak kontrol
# kubectl describe configmap [bu dosyanın adı]