spring:
  application:
    name: "config-server"
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/ergulberke/crm-microservices-config.git"    # config github repo url
          default-label: main  # bizim github sayfalarında master değil main kullanılıyor o yüzden main yaptım hata verirse branch değiştirin

server:
  port: 8089
management:
  endpoints:
    web:
      exposure:
        include: "*"
  enpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  prometheus:
    metrics:
      export:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8888/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: config-server
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30