spring:
  application:
    name: "config-server"
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/ergulberke/crm-microservices-config.git"    # config github repo url
          default-label: main

server:
  port: 8089
management:
  endpoints:
    web:
      exposure:
        include: "*"
  enpoint:
    health:
      show-details: always
  metrics:
    export:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"