spring:
  application:
    name: analytics-service
  datasource:
    url: jdbc:postgresql://localhost:5432/analytics_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    stream:
      bindings:
        userCreatedFunction-in-0:
          destination: user-created-events
          group: analytics-service-group
        subscriptionCreatedFunction-in-0:
          destination: subscription-created-events
          group: analytics-service-group
        billingCreatedFunction-in-0:
          destination: billing-created-events
          group: analytics-service-group
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
          configuration:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            spring.json.trusted.packages: "com.turkcell.analytics_service.event"

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    prefer-ip-address: true

analytics:
  reporting:
    cron: "0 0 0 * * *" # Her gün gece yarısı çalışır 